CREATE TABLE Cities
(
	Id INT IDENTITY UNIQUE NOT NULL,
	[Name] NVARCHAR(20) NOT NULL,
 	CountryCode CHAR(2) NOT NULL,

	CONSTRAINT PK_Cities
	PRIMARY KEY (Id)
)

CREATE TABLE Hotels
(
	Id INT IDENTITY UNIQUE NOT NULL,
	[Name] NVARCHAR(30) NOT NULL,
	CityId INT NOT NULL,
	EmployeeCount INT NOT NULL,
	BaseRate DECIMAL(14, 2),
	
	CONSTRAINT PK_Hotels
	PRIMARY KEY (Id),

	CONSTRAINT FK_Hotels_Cities
	FOREIGN KEY (CityId)
	REFERENCES Cities(Id)
)

CREATE TABLE Rooms
(
	Id INT IDENTITY UNIQUE NOT NULL,
	Price DECIMAL(14, 2) NOT NULL,
	[Type] NVARCHAR(20) NOT NULL,
	Beds INT NOT NULL,
	HotelId INT NOT NULL,

	CONSTRAINT PK_Rooms
	PRIMARY KEY (Id),

	CONSTRAINT FK_Rooms_Hotels
	FOREIGN KEY (HotelId)
	REFERENCES Hotels(Id)
)

CREATE TABLE Trips
(
	Id INT IDENTITY UNIQUE NOT NULL,
	RoomId INT NOT NULL,
	BookDate DATETIME2 NOT NULL,
	ArrivalDate DATETIME2 NOT NULL,
	ReturnDate DATETIME2 NOT NULL,
	CancelDate DATETIME2,

	CONSTRAINT PK_Trips
	PRIMARY KEY (Id),

	CONSTRAINT FK_Trips_Rooms
	FOREIGN KEY (RoomId)
	REFERENCES Rooms(Id),

	CONSTRAINT CHK_Trips_BookDate
	CHECK CAST(BookDate AS DATETIME) < CAST(ArrivalDate AS DATETIME),

	CONSTRAINT CHK_Trips_ArrivalDate
	CHECK (DAY(ArrivalDate) < DAY(ReturnDate))
)

CREATE TABLE Accounts
(
	Id INT IDENTITY UNIQUE NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	MiddleName NVARCHAR(20),
	LastName NVARCHAR(50) NOT NULL,
	CityId INT NOT NULL,
	BirthDate DATETIME2 NOT NULL,
	Email VARCHAR(100) UNIQUE NOT NULL,
	
	CONSTRAINT PK_Accounts
	PRIMARY KEY (Id),

	CONSTRAINT FK_Accounts_Cities
	FOREIGN KEY (CityId)
	REFERENCES Cities(Id)
)

CREATE TABLE AccountsTrips
(
	AccountId INT NOT NULL,
	TripId INT NOT NULL,
	Luggage INT NOT NULL,

	CONSTRAINT FK_AccountsTrips_Accounts
	FOREIGN KEY (AccountId)
	REFERENCES Accounts(Id),

	CONSTRAINT FK_AccountsTrips_Trips
	FOREIGN KEY (TripId)
	REFERENCES Trips(Id),

	CONSTRAINT CHK_AccountsTrips_Luggage
	CHECK (Luggage >= 0)
)